spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: none
      #none?? ?? ??? ????
      #create? ?? ??? ?? ?? ???? ???
    properties:
      hibernate:
        #show_sql: true ??? ?? sout?? ? log? ??? ? ??
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
